objects/Recent_Channel__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Id__c</fullName>
        <label>Channel Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slack_Auth__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Slack Auth</label>
        <referenceTo>Slack_Auth__c</referenceTo>
        <relationshipName>Recent_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recent Channel</label>
    <nameField>
        <label>Recent Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recent Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Slack_Auth__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Most_Recent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Most Recent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Slack_User_Id__c</fullName>
        <label>Slack User Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Slack_Auths</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Workspace_Id__c</fullName>
        <label>Workspace Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workspace__c</fullName>
        <label>Workspace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Slack Auth</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>Slack Auth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Auths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tst_recentChannelTrigger.cls
@isTest
public with sharing class tst_recentChannelTrigger {

    private static FINAL Integer NUMBER_OF_AUTHS = 2;
    private static FINAL Integer NUMBER_OF_CHANNELS = 20;

    @TestSetup
    public static void makeData() {
        
        /* make data */
        List<Slack_Auth__c> authsToInsert = new List<Slack_Auth__c>();
        for (Integer i = 0; i < NUMBER_OF_AUTHS; i++) {
            Slack_Auth__c auth = new Slack_Auth__c();
            auth.User__c = UserInfo.getUserId();
            auth.Workspace__c = 'workspace' + i;
            auth.Is_Most_Recent__c = i == 0 ? true : false;
            auth.Workspace_Id__c = 'workspaceId' + i;
            auth.Slack_User_Id__c = 'slackUserId' + i;
            auth.Access_Token__c = 'accessToken' + i;
            authsToInsert.add(auth);
        }
        insert authsToInsert;

        List<Recent_Channel__c> channelsToInsert = new List<Recent_Channel__c>();
        for (Integer i = 0; i < authsToInsert.size(); i++) {
            for (Integer j = 0; j < NUMBER_OF_CHANNELS; j++) {
                Recent_Channel__c channel = new Recent_Channel__c();
                channel.Slack_Auth__c = authsToInsert[i].Id;
                channel.Name = 'channelName' + j;
                channel.Channel_Id__c = 'channelId' + j;
                channelsToInsert.add(channel);
            }
        }
        insert channelsToInsert;

        /* get inserted data */
        List<Slack_Auth__c> auths = [SELECT Id FROM Slack_Auth__c];
        List<Recent_Channel__c> channels = [SELECT Id FROM Recent_Channel__c];

        /* assert that the data inserted properly */
        System.assertEquals(NUMBER_OF_AUTHS, auths.size(), 'Slack Auth insert failure');
        System.assertEquals((NUMBER_OF_AUTHS * NUMBER_OF_CHANNELS), channels.size(), 'Recent Channel insert failure');
    }

    @isTest
    public static void testMaintainRecentChannelsNoDupe() {
        List<Slack_Auth__c> auths = [SELECT Id FROM Slack_Auth__c];
        Recent_Channel__c channel = new Recent_Channel__c();
        channel.Slack_Auth__c = auths[0].Id;
        channel.Name = 'channelName';
        channel.Channel_Id__c = 'channelId';

        Test.startTest();
        insert channel;
        Test.stopTest();

        List<Recent_Channel__c> newChannelList = [SELECT Id FROM Recent_Channel__c WHERE Slack_Auth__r.Id = :auths[0].Id];

        System.assertEquals(20, newChannelList.size(), 'Channel list is too large');
    }

    @isTest
    public static void testMaintainRecentChannelsWithDupe() {
        List<Slack_Auth__c> auths = [SELECT Id FROM Slack_Auth__c];
        Recent_Channel__c channel = new Recent_Channel__c();
        channel.Slack_Auth__c = auths[0].Id;
        channel.Name = 'channelName0';
        channel.Channel_Id__c = 'channelId0';

        Test.startTest();
        insert channel;
        Test.stopTest();

        List<Recent_Channel__c> newChannelList = [SELECT Id FROM Recent_Channel__c WHERE Slack_Auth__r.Id = :auths[0].Id];

        System.assertEquals(20, newChannelList.size(), 'Channel list is too large');
    }
}