objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Days__c</fullName>
        <description>For demo use</description>
        <label>Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FSL__InJeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>wkfsl__Facility_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility Plan</label>
        <referenceTo>wkfsl__Facility_Plan__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wkfsl__Facility_Plan__c.object
<CustomObject>
    <fields>
        <fullName>wkfsl__AvailabilityRequestsSentDate__c</fullName>
        <description>The date that availability requests were sent to employees for this facility plan.</description>
        <label>Availability Requests Sent On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>wkfsl__Capacity_Overide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override planned occupancy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>wkfsl__Capacity__c</fullName>
        <label>Planned Occupancy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>wkfsl__Completion_Date__c</fullName>
        <description>The due date for employees to submit their availability.</description>
        <inlineHelpText>To be assigned shifts, employees must submit availability by the due date.</inlineHelpText>
        <label>Availability Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>wkfsl__Days_of_the_week__c</fullName>
        <label>Work Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                    <default>true</default>
                    <label>Monday</label>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>wkfsl__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>wkfsl__Generate_Shift__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Create shifts at the lowest level of your location hierarchy. For example, create shifts for spaces but not floors and buildings.</inlineHelpText>
        <label>Create shifts for this location</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>wkfsl__Max_Number_Of_Allowed_Employees__c</fullName>
        <inlineHelpText>Limit the number of people arriving during each time interval.</inlineHelpText>
        <label>Occupancy Per Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>wkfsl__Percentage_Allocation__c</fullName>
        <inlineHelpText>Enter the percentage of the location’s maximum occupancy that your workplace plan allows.</inlineHelpText>
        <label>Reduced Occupancy Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>wkfsl__PlanType__c</fullName>
        <label>Plan Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Managed scheduling</fullName>
                    <default>true</default>
                    <label>Managed scheduling</label>
                </value>
                <value>
                    <fullName>Self-service scheduling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>wkfsl__Related_Top_Level_Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Top Level Territory</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipLabel>Facility Plans</relationshipLabel>
        <relationshipName>Related_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wkfsl__Service_Territory__c</fullName>
        <label>Service Territory Location</label>
        <referenceTo>ServiceTerritory</referenceTo>
        <relationshipLabel>Facility Plans</relationshipLabel>
        <relationshipName>Facility_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>wkfsl__Shifts_Were_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shifts Were Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>wkfsl__Stagger_End_Time__c</fullName>
        <label>Arrival Window End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>wkfsl__Stagger_Start_Time__c</fullName>
        <label>Arrival Window Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>wkfsl__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>wkfsl__Time_Interval__c</fullName>
        <inlineHelpText>Enter the length of each arrival time slot in minutes.</inlineHelpText>
        <label>Arrival Interval</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>wkfsl__Time_To_Stagger__c</fullName>
        <label>Stagger Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>wkfsl__Timezone__c</fullName>
        <label>Timezone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wkfsl__Work_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Work type allows you to set different type of shifts to assign to your employees.</description>
        <inlineHelpText>Assign different type of shifts. Leave blank for default.</inlineHelpText>
        <label>Work Type</label>
        <referenceTo>WorkType</referenceTo>
        <relationshipLabel>Facility Plans</relationshipLabel>
        <relationshipName>Facility_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility Plan</label>
    <nameField>
        <displayFormat>FP-{000000}</displayFormat>
        <label>Facility Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GanttArrivalSurgeService.cls
/**
 * @description       :
 * @author            : Shawn Butters (butters@salesforce.com)
 * @last modified on  : 11-06-2020
 * @last modified by  : shawn.butters
 * Modifications Log
 * Ver   Date         Author                                   Modification
 * 1.0   10-13-2020   Shawn Butters (butters@salesforce.com)   Initial Version
**/
global with sharing class GanttArrivalSurgeService implements FSL.CustomGanttServiceAppointmentAction {

    global String action(List<Id> serviceAppointmentIds, DateTime ganttStartDate, DateTime ganttEndDate, Map<String, Object> additionalParameters) {

        String result = '';

        if (serviceAppointmentIds.isEmpty() || serviceAppointmentIds.size() < 1) {
            return result = 'No Service Appointments were provided for staggering, no action was performed';
        }

        List<ServiceAppointment> ganttAppointments =
                                                    [
                                                        SELECT
                                                            Id,
                                                            ActualEndTime,
                                                            ActualStartTime,
                                                            AppointmentNumber,
                                                            ArrivalWindowEndTime,
                                                            ArrivalWindowStartTime,
                                                            Days__c,
                                                            DueDate,
                                                            EarliestStartTime,
                                                            wkfsl__Facility_Plan__r.Id,
                                                            wkfsl__Facility_Plan__r.Name,
                                                            wkfsl__Facility_Plan__r.wkfsl__PlanType__c,
                                                            wkfsl__Facility_Plan__r.wkfsl__Shifts_Were_Generated__c,
                                                            wkfsl__Facility_Plan__r.wkfsl__Days_of_the_week__c,
                                                            wkfsl__Facility_Plan__r.wkfsl__Related_Top_Level_Territory__r.Id,
                                                            wkfsl__Facility_Plan__r.wkfsl__Timezone__c,
                                                            wkfsl__Facility_Plan__r.wkfsl__Start_Date__c,
                                                            wkfsl__Facility_Plan__r.wkfsl__Service_Territory__r.Id,
                                                            wkfsl__Facility_Plan__r.wkfsl__Time_Interval__c,
                                                            FSL__InJeopardy__c,
                                                            SchedEndTime,
                                                            SchedStartTime,
                                                            Status,
                                                            ServiceTerritory.Id
                                                        FROM ServiceAppointment
                                                        WHERE Id IN :serviceAppointmentIds
                                                    ];

        List<Id> relatedTopLevelTerritoryIds = new List<Id>();

        Map<Id, wkfsl__Facility_Plan__c> facilityPlans;

        for (ServiceAppointment sa : ganttAppointments) {

            relatedTopLevelTerritoryIds.add(sa.wkfsl__Facility_Plan__r.wkfsl__Related_Top_Level_Territory__r.Id);
            //facilityPlans.put(sa.wkfsl__Facility_Plan__r.Id, sa.wkfsl__Facility_Plan__r);
        }

        facilityPlans = new Map<Id, wkfsl__Facility_Plan__c>(
                                                        [
                                                            SELECT
                                                                Id,
                                                                Name,
                                                                wkfsl__AvailabilityRequestsSentDate__c,
                                                                wkfsl__Capacity_Overide__c,
                                                                wkfsl__Capacity__c,
                                                                wkfsl__Completion_Date__c,
                                                                wkfsl__Days_of_the_week__c,
                                                                wkfsl__End_Date__c,
                                                                wkfsl__Generate_Shift__c,
                                                                wkfsl__Max_Number_Of_Allowed_Employees__c,
                                                                wkfsl__Percentage_Allocation__c,
                                                                wkfsl__Related_Top_Level_Territory__c,
                                                                wkfsl__Related_Top_Level_Territory__r.OperatingHours.TimeZone,
                                                                wkfsl__Service_Territory__c,
                                                                wkfsl__Shifts_Were_Generated__c,
                                                                wkfsl__Stagger_End_Time__c,
                                                                wkfsl__Stagger_Start_Time__c,
                                                                wkfsl__Start_Date__c,
                                                                wkfsl__Timezone__c,
                                                                wkfsl__Time_Interval__c,
                                                                wkfsl__Time_To_Stagger__c,
                                                                wkfsl__Work_Type__c
                                                            FROM wkfsl__Facility_Plan__c
                                                            WHERE wkfsl__Related_Top_Level_Territory__r.Id IN :relatedTopLevelTerritoryIds AND wkfsl__Time_Interval__c != NULL
                                                        ]);


        for (wkfsl__Facility_Plan__c plan : facilityPlans.values()) {
            List<wkfsl__Facility_Plan__c> planList = new List<wkfsl__Facility_Plan__c>();
            planList.add(plan);
            Date planStart = plan.wkfsl__Start_Date__c;
            TimeZone planTimeZone = TimeZone.getTimeZone(plan.wkfsl__Related_Top_Level_Territory__r.OperatingHours.TimeZone);
            Date dateToStagger = Date.valueOf(ganttStartDate);
            String dayOfWeekToStartFrom = plan.wkfsl__Days_of_the_week__c.split(';')[0];
            Id thisPlanId = plan.Id;

            // each surge must be on one top level territory plan at a time
            wkfsl.BatchArrivalSurge newSurge = new wkfsl.BatchArrivalSurge(planList, planStart, planTimeZone, dateToStagger, dayOfWeekToStartFrom, thisPlanId);
            System.Database.executeBatch(newSurge);
        }

        result = 'Successfully queued job to calculate arrivals. You might need to refresh to see results if you are viewing weekly.';
        return result;
    }//action()

}//class