objects/Setup_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Namespace_Api__c</fullName>
        <label>Namespace Api</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup Settings</label>
</CustomObject>

objects/Slack_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Async_Limit__c</fullName>
        <label>Async Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trigger_Record_Limit__c</fullName>
        <label>Trigger Record Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Slack Settings</label>
</CustomObject>

classes/postInstall.cls
public with sharing class postInstall implements InstallHandler {
    public void onInstall(InstallContext context) {
        if(context.previousVersion() == null) {
            utilities.generateEncryptionKey();
            Slack_Settings__c slackSettings = Slack_Settings__c.getOrgDefaults();
            slackSettings.Trigger_Record_Limit__c = 5;
            slackSettings.Async_Limit__c = 240000;
            insert slackSettings;
        } else {
            if(context.previousVersion().compareTo(new Version(1,41)) == 0 || context.previousVersion().compareTo(new Version(1,42)) == 0) {
                utilities.generateEncryptionKey();
            }

            Slack_Settings__c slackSettings = Slack_Settings__c.getOrgDefaults();

            if(slackSettings.Async_Limit__c == null){
                slackSettings.Async_Limit__c = 240000;
                upsert slackSettings;
            }
        }


        Setup_Settings__c settings = Setup_Settings__c.getOrgDefaults();

        if(settings.Namespace_Api__c == null){
            settings.Namespace_Api__c = constants.NAMESPACE_API;
            upsert settings;
        }
    }
}