objects/Slack_Message__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Slack Messages</relationshipLabel>
        <relationshipName>Slack_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Slack Messages</relationshipLabel>
        <relationshipName>Slack_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Slack Messages</relationshipLabel>
        <relationshipName>Slack_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Slack Messages</relationshipLabel>
        <relationshipName>Slack_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Slack Messages</relationshipLabel>
        <relationshipName>Slack_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Slack Message</label>
    <nameField>
        <displayFormat>SM-{0000000}</displayFormat>
        <label>Slack Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/slackMessageTrigger.cls
public with sharing class slackMessageTrigger {

    public static void updateLookupId(List<Slack_Message__c> newMessages) {
        Map<String, Map<String, Set<String>>> accessChecks = new Map<String, Map<String, Set<String>>> {
            'Slack_Message__c' => new Map<String, Set<String>> {
                'Update' => new Set<String> {
                    'Account__c', 'Contact__c', 'Lead__c', 'Case__c', 'Opportunity__c'
                }
            }
        };
        dmlManager.checkAccess(accessChecks);

        for (Slack_Message__c message : newMessages) {
            ID primitiveRecordId = message.Record_Id__c;
            String sobjectTypeName = primitiveRecordId.getSObjectType().getDescribe().getName();
            switch on sobjectTypeName {
                when 'Account' {
                    message.Account__c = primitiveRecordId;
                }
                when 'Contact' {
                    message.Contact__c = primitiveRecordId;
                }
                when 'Lead' {
                    message.Lead__c = primitiveRecordId;
                }
                when 'Case' {
                    message.Case__c = primitiveRecordId;
                }
                when 'Opportunity' {
                    message.Opportunity__c = primitiveRecordId;
                }
            }
        }
    }

}