objects/trailheadapp__Badge__c.object
<CustomObject>
    <description>Available Trailhead badges.</description>
    <fields>
        <fullName>trailheadapp__External_Id__c</fullName>
        <description>This field has been deprecated and is no longer being used.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field has been deprecated and is no longer being used.</inlineHelpText>
        <label>External Id</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/trailheadapp__User_Badge__c.object
<CustomObject>
    <description>Junction object for badges and users.</description>
    <fields>
        <fullName>trailheadapp__Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>trailheadapp__Badge__c</referenceTo>
        <relationshipLabel>User Badge</relationshipLabel>
        <relationshipName>User_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>trailheadapp__External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>trailheadapp__Finished_Date__c</fullName>
        <label>Finished Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>trailheadapp__First_Attempted_Date__c</fullName>
        <description>The date the badge was attempted.</description>
        <label>First Attempted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>trailheadapp__Last_Attempted_Date__c</fullName>
        <description>Date the badge was last attempted.</description>
        <label>Last Attempted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>trailheadapp__Status__c</fullName>
        <defaultValue>&quot;Assigned&quot;</defaultValue>
        <description>Three types of status, &quot;Assigned&quot;, &quot;In Progress&quot;, or &quot;Completed&quot; are available to represent the status of a user&apos;s badge. While we always expect a value, this is not a required field to enable FLS for badge assigners.</description>
        <inlineHelpText>Three types of status, &quot;Assigned&quot;, &quot;In Progress&quot;, or &quot;Completed&quot; are available to represent the status of a user&apos;s badge</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>trailheadapp__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trailhead_User_Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Badge</label>
    <nameField>
        <displayFormat>BADGE-{0000}</displayFormat>
        <label>User Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrailheadSetupScript.cls
public class TrailheadSetupScript {
    public static void createBadgesForUser(String userId, Integer numBadges) {
        // this record should show up in the results since it's completed 2 days ago
        trailheadapp__User_Badge__c ub4 = new trailheadapp__User_Badge__c();
        ub4.trailheadapp__Badge__c = [select id from trailheadapp__badge__c where name = 'Workflow Rule Migration'].Id;
        ub4.trailheadapp__User__c = userId;
        ub4.trailheadapp__External_ID__c = ub4.trailheadapp__User__c + '-' + ub4.trailheadapp__Badge__c;                        
        ub4.trailheadapp__Finished_Date__c = Date.today().addDays(-2);
        ub4.trailheadapp__First_Attempted_Date__c = Date.today();
        ub4.trailheadapp__Last_Attempted_Date__c = Date.today();
        ub4.trailheadapp__Status__c = 'Completed';
        insert ub4;        
        
        if (numBadges > 1) {
            // this record should show NOT up in the results since it's 'assigned'
            trailheadapp__User_Badge__c ub5 = new trailheadapp__User_Badge__c();
            ub5.trailheadapp__Badge__c = [select id from trailheadapp__badge__c where name = 'Apex Basics for Admins'].Id;
            ub5.trailheadapp__User__c = userId;
            ub5.trailheadapp__External_ID__c = ub5.trailheadapp__User__c + '-' + ub5.trailheadapp__Badge__c;                        
            ub5.trailheadapp__Finished_Date__c = Date.today().addDays(-2);
            ub5.trailheadapp__First_Attempted_Date__c = Date.today();
            ub5.trailheadapp__Last_Attempted_Date__c = Date.today();
            ub5.trailheadapp__Status__c = 'Assigned'; // <<<<--------------
            insert ub5;     
        }         
        
        if(numBadges > 2) {
            // this record should show NOT up in the results since it's completed 30 days ago
            trailheadapp__User_Badge__c ub6 = new trailheadapp__User_Badge__c();
            ub6.trailheadapp__Badge__c = [select id from trailheadapp__badge__c where name = 'Asynchronous Apex'].Id;
            ub6.trailheadapp__User__c = userId;
            ub6.trailheadapp__External_ID__c = ub6.trailheadapp__User__c + '-' + ub6.trailheadapp__Badge__c;                        
            ub6.trailheadapp__Finished_Date__c = Date.today().addDays(-30); // <<<<--------------
            ub6.trailheadapp__First_Attempted_Date__c = Date.today();
            ub6.trailheadapp__Last_Attempted_Date__c = Date.today();
            ub6.trailheadapp__Status__c = 'Completed'; 
            insert ub6;   
        }
    }
}