objects/wkcc__LocationWellnessFact__c.object
<CustomObject>
    <description>This object aggregates individual wellness counts by location and status.  Directly related counts are maintained for level-1 locations.  Cascading counts are maintained for level-1 and level-2 locations.</description>
    <fields>
        <fullName>wkcc__ExternalId__c</fullName>
        <description>A unique identifier for the record in the format [&quot;Cascade&quot; + &quot;:&quot; +] &lt;Location Id&gt; + ‘:’ + &lt;Wellness Status&gt;. The cascade prefix is only present in records that include child location wellness status values.</description>
        <externalId>true</externalId>
        <inlineHelpText>A unique identifier for the record in the format [&quot;Cascade&quot; + &quot;:&quot; +] &lt;Location Id&gt; + ‘:’ + &lt;Wellness Status&gt;. The cascade prefix is only present in records that include child location wellness status values.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>wkcc__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location that this fact record relates to</description>
        <inlineHelpText>The location that this fact record relates to.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Location Wellness Facts</relationshipLabel>
        <relationshipName>LocationWellnessFacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location Wellness Fact</label>
    <nameField>
        <displayFormat>LWF-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Wellness Facts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/wkcc__LocationWellnessStaging__c.object
<CustomObject>
    <description>This object is a staging table for re-calculating location wellness facts.  Records are removed once the locations have been recalculated.</description>
    <fields>
        <fullName>wkcc__ExternalId__c</fullName>
        <description>A unique identifier for the record in the format of &lt;Location Id&gt; + ‘:’ + &lt;Wellness Status&gt;.</description>
        <externalId>true</externalId>
        <inlineHelpText>A unique identifier for the record in the format of &lt;Location Id&gt; + ‘:’ + &lt;Wellness Status&gt;.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>wkcc__JobStatus__c</fullName>
        <defaultValue>&quot;Not Processed&quot;</defaultValue>
        <description>Indicates the status of this location for processing.</description>
        <inlineHelpText>Indicates the status of this location for processing.</inlineHelpText>
        <label>Job Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Processed</fullName>
                    <default>true</default>
                    <label>Not Processed</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>wkcc__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location that needs its fact records recalculated.</description>
        <inlineHelpText>The location that needs its fact records recalculated.</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Location Wellness Staging</relationshipLabel>
        <relationshipName>LocationWellnessStaging</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location Wellness Staging</label>
    <nameField>
        <displayFormat>LWS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Wellness Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WdcDemo_WellnessRecalcBatchable.cls
global class WdcDemo_WellnessRecalcBatchable implements Database.Batchable<SObject> {

    global final String query = 'SELECT Id FROM Location';

    // final member variable for status
    private static final String WELLNESS_FACT_STATUS = 'NOT PROCESSED';

    global WdcDemo_WellnessRecalcBatchable () {
        //default constructor
    }

    global WdcDemo_WellnessRecalcBatchable ( String q ) {
        this.query = q;
    }

    global Database.QueryLocator start(Database.BatchableContext BC_START) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC_EXEC, List<SObject> scope) {

        if(scope == null) return;

        // instantiate new list for insertion later
        List<wkcc__LocationWellnessStaging__c> lLocWellnessToInsert = new List<wkcc__LocationWellnessStaging__c>();

        // Begin primary logic
        if(scope[0] instanceof Schema.Location) {

            // convert to list of ids
            List<Id> lLocationIds = new List<Id>();
            for(Schema.Location loc : (List<Schema.Location>)scope) {
                lLocationIds.add(loc.Id);
            }

            // delete staged welleness using list of ids in query
            Database.delete([SELECT Id FROM wkcc__LocationWellnessStaging__c]);

            // delete all wellness facts as they are about to be recalculated
            Database.delete([SELECT Id FROM wkcc__LocationWellnessFact__c]);

            // create new staging records and insert them
            for(Schema.Location loc : (List<Schema.Location>)scope) {
                lLocWellnessToInsert.add( new wkcc__LocationWellnessStaging__c(
                        wkcc__Location__c = loc.Id,
                        wkcc__JobStatus__c = WELLNESS_FACT_STATUS,
                        wkcc__ExternalId__c = loc.Id + ',' + WELLNESS_FACT_STATUS
                    )
                );

            }
        }
        else {

            throw new System.SerializationException('Data in scope is not of the correct type.');
        }
        // end logical processing

        // create new location wellness facts that will cause re-calculation
        if( lLocWellnessToInsert != null ) {
            Database.insert(lLocWellnessToInsert);
        }
    }
    // end execute

    global void finish(Database.BatchableContext BC_FIN) {
        //implement me
    }

}